serverselector_name: '&bServer Selector &8(Right Click)'
nogadget_name: '&bGadget: &cNo gadget equipped!'
cosmetics_name: '&bCosmetics &8(Right Click)'
hidervisible_name: '&fPlayers: &aVisible &8(Right Click)'